### ISSUE TITLE
Insteed of 6 - the easy way to coordinate Java development by several teams

### ISSUE THREAD

**Issue by PavelSosin-320** [jcuda/jcuda-samples#7]
Threre are few simple steps which can ease coordination:

1. Label rcurrent project state as release candidate to postpone dealing with release procedure
2. Use intermediate Nexus repository before posting version to Maven Central. It is very simple to install Nexus and add Nexus repository to maven configuration for every developer. Nexus doesn't need even server because it can be deployed to any claud infra as Nexus Docker container. Everybody can submit changes to Nexus without formal release.
Everybody can build his/her own project master branch using core project release candidate
Development pipeline of every team can use Nexus in its development and automated testing

**Comment by jcuda** [comment]
I appreciate comments that aim at improving the deployment and development. But frankly: I'm not sure what I should do with this one. 

I know that there are sophisticated build infrastructures out there, and DevOps guys spending their whole day with tweaking some Jenkins configuration files and so on. But first of all: There is no "team". JCuda is a spare time project. I'm just a nerd who <strike>has</strike> once had a bit too much spare time, and thought: Hey, people could find this useful. The development process of JCuda had therefore been *very* ... let's say, "pragmatic" for a long time: I developed it locally, and then dumped the code+binaries on the jcuda.org "Downloads" site. 

The process of bringing JCuda into Maven central was difficult. Up to ~JCuda 7.0 or so, it did not use Maven at all. And you probably cannot imagine how fiddly the handling of native libraries can be, *particularly* when they are supposed to work with Maven. But this was tackled eventually in https://github.com/jcuda/jcuda-main/issues/14  . Now, people seem to be happy with what they get.

I won't deny that the release process involves several manual steps and is a bit tedious. But when I have the choice of 1. either running a bunch of .BAT files once or twice a year and upload some JARs to sonatype, or 2. maintaining some sophisticated virtual nexus docker cloud build server infrastructure, I'd prefer option 1, because I'd probably have to invest weeks or months initially to get option 2 up and running, and even if it was simple to get this running smoothly (which it almost definitely isn't), it would still have to be maintained and monitored (any maybe even paid for?) constantly. 

Again: Contributions are welcome. And I'd **really** appreciate a simplification for the release process. But I cannot become a professional DevOps engineer in my spare time.

**Comment by jcuda** [comment]
As long as there are no specific goals or tasks that can be derived from that, I'm closing this one.
