### ISSUE TITLE
Universal Callable ad Runnable Wrappers and thread safety test

### ISSUE THREAD

**Issue by PavelSosin-320** [jcuda/jcuda-samples#8]
To run Java cuda applications as regular ( not main ) class Collable and Runable wrappers are the prerequisit. Running Collable and Runnable classes requirs thread safety test. Both are almost done. I will assign these issues to myself

**Comment by jcuda** [comment]
I'm not sure what this is aiming at, but if the goal is to show that it's easy to crash a CUDA/JCuda application without synchronization: I know that, and I wrote a somewhat extensive answer at https://github.com/jcuda/jcuda/issues/25#issuecomment-541759398

In any case: Please do the same test in C++, so that we have a comparison to plain CUDA.

**Comment by jcuda** [comment]
If there are any specific results (issues) or tasks that can be derived from that, just let me know.
