### ISSUE TITLE
Cuda 11 support: UnsatisfiedLinkError

### ISSUE THREAD

**Issue by maroony** [jcuda/jcuda-samples#9]
I would like to run some sample classes with Cuda 11 and JCuda 10.2.0. There seems to be compatibility problems:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Error while loading native library "JCurand-10.2.0-windows-x86_64"
```

Are there any plans to support Cuda 11?

**Comment by jcuda** [comment]
Yes, sorry, the update for CUDA 11 took way longer than it should have. The update is discussed in https://github.com/jcuda/jcuda-main/issues/35 , and the binaries are already available, but I still have to upload them. I'll try to do this today (or not later than tomorrow). 

Afterwards, I will also update of the `jcuda-samples` so that they use JCuda 11.0.0.

I'll drop a note here when it's done.

**Comment by jcuda** [comment]
JCuda 11.0.0 has just been released. The samples have been updated accordingly. 

(Note that some samples had to be removed due to the deprecation of nvGRAPH and API changes that would require further updates).

If you encounter any problems, either open an issue or reopen this one, if appropriate.
